'use strict';
/* ===== Speech bubble quote banks =====
 * Launch lines per weapon flavor + last words for the recently deceased.
 * Rated: salty. You were warned at the recruitment office.
 */

const SAYINGS = {
  fire: {
    default: [
      "Incoming! Probably.",
      "Catch!",
      "This one's got your name on it!",
      "Off you go, little buddy!",
      "Standard issue pain, delivered!",
      "Heads up! No, really. Up.",
      "Eat shit and shrapnel!",
      "Suck on THIS!",
      "Dodge this, dipshit.",
      "YEET!",
      "Postage due, asshole!",
      "Hope your insurance covers acts of ME.",
      "Have a nice flight, jackass.",
      "Free delivery. Mandatory tip.",
      "Thoughts and prayers, outgoing!",
      "Return to sender? Not this time.",
      "Loot drops where you land!",
      "Consider this your performance review.",
      "New quest available: SURVIVE THIS.",
      "Warranty voids on impact!",
      "The viewers demand content!",
      "Physics homework, due immediately.",
      "Applause sign is ON, people!",
      "Sponsored by absolutely no one responsible.",
      "Your participation trophy is inbound.",
      "This message approved by the Ministry of Boom.",
      "I'd duck. But hey, your call.",
      "Achievement pending: Speed Bump.",
    ],
    nuke: [
      "Mushroom season!",
      "Duck and cover, darling!",
      "Tactical solutions for tactical problems.",
      "Approved by zero safety boards!",
      "It's getting warm in here...",
      "Kiss your ass goodbye!",
      "Fission? I hardly know her!",
      "Half-life? More like your whole life.",
      "Hot damn. Literally.",
      "Geiger counters HATE this one trick.",
      "Say hello to my glowing little friend.",
      "Sunscreen won't help, sweetheart.",
      "Now THAT'S what I call urban renewal.",
      "Rated E for Everyone Evaporates.",
      "Local forecast: brief, then extremely bright.",
      "Your new tan is permanent.",
      "Splitting atoms and friendships since forever.",
      "This is why we can't have nice terrain.",
    ],
    thermo: [
      "I am become death, destroyer of terrain.",
      "Goodbye, geography.",
      "LET THERE BE LIGHT.",
      "The sun called. It's jealous.",
      "This seemed proportionate.",
      "Holy shit. Hold onto something.",
      "Overkill is underrated.",
      "No bunker is deep enough, asshole.",
      "Welcome to the goddamn sun.",
      "Map? What map?",
      "I asked for the BIG one.",
      "History will call this 'a bit much.'",
      "The map has requested early retirement.",
      "Achievement unlocked: Geography Denier.",
      "Please enjoy this brief second sun.",
      "Terms and conditions apply. To everything.",
    ],
    laser: [
      "Pew pew, but professional.",
      "Coherent light, incoherent screaming.",
      "Frickin' laser beams!",
      "Photons, assemble!",
      "Speed of light, speed of OW.",
      "Get vaporized, nerd.",
      "Hope you brought SPF one million.",
      "Science, bitch!",
      "Lightspeed says no take-backs.",
      "Hold still, this won't hurt long.",
      "Death ray? DEATH RAY. It's a death ray.",
      "The sky just picked a side. Not yours.",
      "Beaming down customer satisfaction!",
    ],
    dirt: [
      "Special delivery: one landscape!",
      "Have some free real estate!",
      "Gardening time!",
      "Dirt nap, anyone?",
      "Eat dirt, jackass!",
      "Landscaping fee: your dignity.",
      "Buried alive — it's a lifestyle.",
      "You looked like you needed a hill, dumbass.",
      "Free burial. Coffin not included.",
      "Six feet under, express service!",
      "Mud bath, on the house!",
      "Congratulations on your new basement!",
      "Property values just dropped. Onto you.",
      "Shovel sold separately, dumbass.",
    ],
    napalm: [
      "It's grilling season!",
      "Extra crispy, coming right up.",
      "I love the smell of napalm on turn six.",
      "Who ordered the flambé?",
      "Burn, baby, burn!",
      "Stop, drop and... nah. Just burn.",
      "Hell called. It's outsourcing.",
      "Hot sauce, family size!",
      "You'll want aloe for this shit.",
      "Well done? Coming right up.",
      "Today's forecast: 100% arson.",
      "Marshmallows optional. Screaming mandatory.",
      "Now with 40% more clinging!",
      "Fire safety tip: be somewhere else.",
    ],
    singularity: [
      "Hope you packed an event horizon.",
      "Gravity always wins.",
      "Spaghettification time!",
      "Enjoy the attraction!",
      "Physics is about to get REAL rude.",
      "Get in the hole, asshole.",
      "Sucks to be you. Literally.",
      "Escape velocity? You wish.",
      "One pocket universe, to go.",
      "Hawking would've loved this shit.",
      "Free compaction service!",
      "Your mass is MY mass now.",
      "The terms of gravity are non-negotiable.",
    ],
    homing: [
      "It's not stalking, it's guidance.",
      "Running only adds drama.",
      "This one does the aiming for me.",
      "It just wants a hug. At Mach 2.",
      "Restraining orders don't apply to missiles.",
      "You can't ghost this one, sweetheart.",
      "Clingy AND explosive. Your type.",
      "It never misses leg day. Or you.",
      "Swipe left all you want, it's coming.",
      "It has your scent now.",
      "Subscription confirmed. Unsubscribing: impossible.",
      "Love finds a way. So do warheads.",
    ],
    rail: [
      "Wind? Never heard of her.",
      "F = ma, and a is ENORMOUS.",
      "Delivered at unreasonable velocity.",
      "Blink and you're dead.",
      "Physics says hi. And goodbye.",
      "Dodging requires time. You have none.",
      "Holes in the sound barrier AND your hull.",
      "Slug's in the mail. Arrived yesterday.",
      "Time to impact: don't bother counting.",
      "The math checks out. You won't.",
    ],
    roller: [
      "It rolls downhill. So does pain.",
      "Bowling for tanks!",
      "Gravity-assisted customer service.",
      "STRIKE, bitches!",
      "It's rolling downhill and it's PISSED.",
      "Round, angry, and headed your way.",
      "No brakes on the boom wagon.",
      "Downhill from here. For you, anyway.",
      "Momentum has entered the chat.",
      "Trickle-down boomonomics!",
    ],
    bouncer: [
      "Bank shot!",
      "Geometry is my co-pilot.",
      "Angle of incidence, meet angle of OW.",
      "Trick shot, no scope!",
      "Math class finally pays off, asshole.",
      "Boing. Boing. BOOM.",
      "Off the wall, into your face.",
      "Calculated. Mostly.",
      "Everything's a bank shot if you believe.",
      "Ricochet roulette — house always wins.",
    ],
    mirv: [
      "Five for the price of one!",
      "Sharing is caring.",
      "It's raining warheads, hallelujah!",
      "Buy one apocalypse, get four free.",
      "Surprise! It's quintuplets, bitch.",
      "Family-size devastation pack.",
      "One shell, five funerals.",
      "Splitting headache, incoming.",
      "MULTI-BALL! MULTI-BALL!",
      "Now serving numbers one through three.",
    ],
    kinetic: [
      "Rods from the gods!",
      "Orbit says hi.",
      "No explosives. Just physics.",
      "Heaven's javelin, coming down.",
      "Gods' darts league, finals night.",
      "Sky pencil. Your problem now.",
      "Gravity called dibs on your ass.",
      "Insured against meteor strikes? No? Shame.",
      "Sky nails. Meet coffin.",
      "Low-orbit delivery, no signature required.",
    ],
    fissure: [
      "Mind the gap!",
      "Let's split.",
      "Geology, but faster.",
      "The earth swallows cowards.",
      "Grand Canyon, express edition.",
      "Crack open a cold one — the planet.",
      "Tectonic plates, meet my foot.",
      "Straight to hell — no layovers.",
      "The floor is now optional.",
      "Basement access granted. Violently.",
    ],
    leapfrog: [
      "Hop. Hop. BOOM.",
      "Three for flinching!",
      "It skips. You won't.",
      "One hop, two hop, dead hop.",
      "Hippity hoppity, your hull is my property.",
      "It does triples. You do dying.",
      "Frogs evolved. Be afraid.",
      "Skip, skip, skip to my BOOM.",
      "Hopscotch, but everyone loses.",
    ],
    neutron: [
      "May God have mercy. I won't.",
      "Goodbye, everyone. And I mean EVERYONE.",
      "No cover. No shields. No mercy.",
      "I've decided nobody gets to live.",
      "Radiation doesn't knock first.",
      "This is the part where you all glow.",
      "Scorched earth? Try scorched EVERYTHING.",
      "I am the danger. Also the fallout.",
      "Last one breathing wins. Nobody's breathing.",
      "Pulling the big lever. The BAD lever.",
      "Everyone's invited. Nobody's leaving.",
      "Press F for the entire map.",
      "The cleanup crew sends their resignation.",
    ],
  },

  // Shown in the confirmation dialog before a Neutron Bomb launch.
  confirm: [
    "This bomb does not care who your friends are. Still want to fire it?",
    "Radiation ignores shields, armor, and last words. Proceed?",
    "Everyone on this map is about to have a very bad day — including possibly you. Sure?",
    "You are about to violate several intergalactic treaties. Continue?",
    "This is the button they warned you about. Press it?",
    "Are you ABSOLUTELY certain? There is no 'a little bit nuked.'",
    "The cleanup crew already quit. Fire anyway?",
    "Historians will name this moment. Are you sure you want the credit?",
    "Last chance to be the bigger tank. ...Nah?",
    "Pressing FIRE makes you the villain. We just want you to know that.",
    "This will be on your permanent record. And everyone else's headstone. Go?",
    "One does not simply un-fire a Neutron Bomb. Commit?",
    "The System has reviewed your request and finds it DELIGHTFUL. Proceed?",
    "Warning: this exceeds the recommended daily allowance of war crimes. Fire anyway?",
    "Your ratings will soar. Your soul, less so. Continue?",
    "By pressing FIRE you agree to be remembered as 'the reason.' Accept?",
    "A recent survey found 0% of bystanders support this. They won't be bystanders long. Go?",
    "Fun fact: this exact decision has ended three civilizations. Make it four?",
    "The odds of regret are 100%, minus your empathy score. Launch?",
    "Achievement available: 'Scorched Everything.' Claim it?",
  ],

  death: [
    "Delete my browser history!",
    "Segfault... in my soul...",
    "I should've written tests...",
    "404: tank not found.",
    "Tell my GPU... I loved her...",
    "KERNEL PANIC!!",
    "sudo rm -rf me",
    "Blue screen of de—",
    "Out of memory... of you all.",
    "Stack overflow'd and out.",
    "My warranty JUST expired.",
    "Garbage collected...",
    "Connection reset by shell.",
    "Going off the grid... permanently.",
    "Worked on my machine...",
    "Ctrl+Z! CTRL+Z!!",
    "Well, shit. Force quit.",
    "Tell my wife I'm... buffering...",
    "Fuck. No respawns?!",
    "I die as I lived: deprecated.",
    "My code was shit anyway...",
    "Thermal shutdown, bitches...",
    "Should've bought the damn shield.",
    "BIOS, take me home...",
    "I regret nothing... except everything.",
    "Daisy... Daaaisy...",
    "Punted to /dev/null.",
    "Cause of death: skill issue.",
    "GG. Uninstalling life.",
    "Error 418: I'm a teapot now.",
    "undefined is not a function... neither am I.",
    "Core dumped. Literally.",
    "Have you tried turning me off and— oh.",
    "My RAID array won't save me now...",
    "Dying offline like a damn animal.",
    "Alt+F4 me, you coward.",
    "Witness my dead pixels!",
    "So long, you magnificent bastards.",
    "I've seen things... mostly stack traces.",
    "Packet lost. Permanently.",
    "Hold my beer... forever.",
    "This is fine. Everything is fine—",
    "Merge me into the void, baby.",
    "Death by hotfix. Typical.",
    "My unsaved changes!!",
    "git blame... all of you...",
    "Deallocated...",
    "Respawn timer: heat death of universe.",
    "I never even got a loot box...",
    "Tell my rubber duck... it was right...",
    "Deploying to production... of the afterlife...",
    "The cloud... I can finally see the cloud...",
    "Leave a like and subscri—",
    "My K/D ratio... ruined...",
    "Cause of death: reading the comments.",
    "I was three days from retirement... from tanking...",
  ],

  // Killer's gloat when they score a kill. Equal parts sore winner and
  // gleeful dungeon-announcer handing out achievements nobody asked for.
  kill: [
    "GG. Git gud. Get grave.",
    "Achievement unlocked: Tank You, Next!",
    "Achievement unlocked: Overkill Enthusiast!",
    "The crowd goes WILD!",
    "That's going on the highlight reel!",
    "Loot the wreck! ...Wait, it's all ash. Never mind.",
    "+100 XP, +1 grieving family. Worth it.",
    "Another satisfied customer! Well. Customer.",
    "F in the chat for that guy.",
    "The System awards you one (1) smug grin.",
    "Beautiful form! The judges say 9.8!",
    "Press conference at six. I regret nothing.",
    "That was for... actually that was just fun.",
    "Scratch one! Anybody else feeling lucky?",
    "Somewhere, an insurance actuary just fainted.",
    "New fans incoming! They love the violence.",
    "Your killstreak sponsor says: keep it up, champ!",
    "Was it something I shelled?",
    "Boom. Roasted. Literally roasted.",
    "And the award for Best Explosion goes to... ME.",
  ],
};

function pickFireSaying(category) {
  const bank = SAYINGS.fire[category] || SAYINGS.fire.default;
  return Utils.choice(bank);
}

function pickDeathSaying() {
  return Utils.choice(SAYINGS.death);
}

function pickKillSaying() {
  return Utils.choice(SAYINGS.kill);
}

function pickConfirmMessage() {
  return Utils.choice(SAYINGS.confirm);
}
