'use strict';
/* ===== Speech bubble quote banks =====
 * Launch lines per weapon flavor + last words for the recently deceased.
 * Rated: salty. You were warned at the recruitment office.
 */

const SAYINGS = {
  fire: {
    default: [
      "Incoming! Probably.",
      "Catch!",
      "This one's got your name on it!",
      "Off you go, little buddy!",
      "Standard issue pain, delivered!",
      "Heads up! No, really. Up.",
      "Eat shit and shrapnel!",
      "Suck on THIS!",
      "Dodge this, dipshit.",
      "YEET!",
      "Postage due, asshole!",
      "Hope your insurance covers acts of ME.",
      "Have a nice flight, jackass.",
      "Free delivery. Mandatory tip.",
      "Thoughts and prayers, outgoing!",
      "Return to sender? Not this time.",
    ],
    nuke: [
      "Mushroom season!",
      "Duck and cover, darling!",
      "Tactical solutions for tactical problems.",
      "Approved by zero safety boards!",
      "It's getting warm in here...",
      "Kiss your ass goodbye!",
      "Fission? I hardly know her!",
      "Half-life? More like your whole life.",
      "Hot damn. Literally.",
      "Geiger counters HATE this one trick.",
      "Say hello to my glowing little friend.",
      "Sunscreen won't help, sweetheart.",
      "Now THAT'S what I call urban renewal.",
    ],
    thermo: [
      "I am become death, destroyer of terrain.",
      "Goodbye, geography.",
      "LET THERE BE LIGHT.",
      "The sun called. It's jealous.",
      "This seemed proportionate.",
      "Holy shit. Hold onto something.",
      "Overkill is underrated.",
      "No bunker is deep enough, asshole.",
      "Welcome to the goddamn sun.",
      "Map? What map?",
      "I asked for the BIG one.",
      "History will call this 'a bit much.'",
    ],
    laser: [
      "Pew pew, but professional.",
      "Coherent light, incoherent screaming.",
      "Frickin' laser beams!",
      "Photons, assemble!",
      "Speed of light, speed of OW.",
      "Get vaporized, nerd.",
      "Hope you brought SPF one million.",
      "Science, bitch!",
      "Lightspeed says no take-backs.",
      "Hold still, this won't hurt long.",
    ],
    dirt: [
      "Special delivery: one landscape!",
      "Have some free real estate!",
      "Gardening time!",
      "Dirt nap, anyone?",
      "Eat dirt, jackass!",
      "Landscaping fee: your dignity.",
      "Buried alive — it's a lifestyle.",
      "You looked like you needed a hill, dumbass.",
      "Free burial. Coffin not included.",
      "Six feet under, express service!",
      "Mud bath, on the house!",
    ],
    napalm: [
      "It's grilling season!",
      "Extra crispy, coming right up.",
      "I love the smell of napalm on turn six.",
      "Who ordered the flambé?",
      "Burn, baby, burn!",
      "Stop, drop and... nah. Just burn.",
      "Hell called. It's outsourcing.",
      "Hot sauce, family size!",
      "You'll want aloe for this shit.",
      "Well done? Coming right up.",
      "Today's forecast: 100% arson.",
    ],
    singularity: [
      "Hope you packed an event horizon.",
      "Gravity always wins.",
      "Spaghettification time!",
      "Enjoy the attraction!",
      "Physics is about to get REAL rude.",
      "Get in the hole, asshole.",
      "Sucks to be you. Literally.",
      "Escape velocity? You wish.",
      "One pocket universe, to go.",
      "Hawking would've loved this shit.",
    ],
    homing: [
      "It's not stalking, it's guidance.",
      "Running only adds drama.",
      "This one does the aiming for me.",
      "It just wants a hug. At Mach 2.",
      "Restraining orders don't apply to missiles.",
      "You can't ghost this one, sweetheart.",
      "Clingy AND explosive. Your type.",
      "It never misses leg day. Or you.",
      "Swipe left all you want, it's coming.",
    ],
    rail: [
      "Wind? Never heard of her.",
      "F = ma, and a is ENORMOUS.",
      "Delivered at unreasonable velocity.",
      "Blink and you're dead.",
      "Physics says hi. And goodbye.",
      "Dodging requires time. You have none.",
      "Holes in the sound barrier AND your hull.",
      "Slug's in the mail. Arrived yesterday.",
    ],
    roller: [
      "It rolls downhill. So does pain.",
      "Bowling for tanks!",
      "Gravity-assisted customer service.",
      "STRIKE, bitches!",
      "It's rolling downhill and it's PISSED.",
      "Round, angry, and headed your way.",
      "No brakes on the boom wagon.",
      "Downhill from here. For you, anyway.",
    ],
    bouncer: [
      "Bank shot!",
      "Geometry is my co-pilot.",
      "Angle of incidence, meet angle of OW.",
      "Trick shot, no scope!",
      "Math class finally pays off, asshole.",
      "Boing. Boing. BOOM.",
      "Off the wall, into your face.",
      "Calculated. Mostly.",
    ],
    mirv: [
      "Five for the price of one!",
      "Sharing is caring.",
      "It's raining warheads, hallelujah!",
      "Buy one apocalypse, get four free.",
      "Surprise! It's quintuplets, bitch.",
      "Family-size devastation pack.",
      "One shell, five funerals.",
      "Splitting headache, incoming.",
    ],
    kinetic: [
      "Rods from the gods!",
      "Orbit says hi.",
      "No explosives. Just physics.",
      "Heaven's javelin, coming down.",
      "Gods' darts league, finals night.",
      "Sky pencil. Your problem now.",
      "Gravity called dibs on your ass.",
      "Insured against meteor strikes? No? Shame.",
    ],
    fissure: [
      "Mind the gap!",
      "Let's split.",
      "Geology, but faster.",
      "The earth swallows cowards.",
      "Grand Canyon, express edition.",
      "Crack open a cold one — the planet.",
      "Tectonic plates, meet my foot.",
      "Straight to hell — no layovers.",
    ],
    leapfrog: [
      "Hop. Hop. BOOM.",
      "Three for flinching!",
      "It skips. You won't.",
      "One hop, two hop, dead hop.",
      "Hippity hoppity, your hull is my property.",
      "It does triples. You do dying.",
      "Frogs evolved. Be afraid.",
    ],
  },

  death: [
    "Delete my browser history!",
    "Segfault... in my soul...",
    "I should've written tests...",
    "404: tank not found.",
    "Tell my GPU... I loved her...",
    "KERNEL PANIC!!",
    "sudo rm -rf me",
    "Blue screen of de—",
    "Out of memory... of you all.",
    "Stack overflow'd and out.",
    "My warranty JUST expired.",
    "Garbage collected...",
    "Connection reset by shell.",
    "Going off the grid... permanently.",
    "Worked on my machine...",
    "Ctrl+Z! CTRL+Z!!",
    "Well, shit. Force quit.",
    "Tell my wife I'm... buffering...",
    "Fuck. No respawns?!",
    "I die as I lived: deprecated.",
    "My code was shit anyway...",
    "Thermal shutdown, bitches...",
    "Should've bought the damn shield.",
    "BIOS, take me home...",
    "I regret nothing... except everything.",
    "Daisy... Daaaisy...",
    "Punted to /dev/null.",
    "Cause of death: skill issue.",
    "GG. Uninstalling life.",
    "Error 418: I'm a teapot now.",
    "undefined is not a function... neither am I.",
    "Core dumped. Literally.",
    "Have you tried turning me off and— oh.",
    "My RAID array won't save me now...",
    "Dying offline like a damn animal.",
    "Alt+F4 me, you coward.",
    "Witness my dead pixels!",
    "So long, you magnificent bastards.",
    "I've seen things... mostly stack traces.",
    "Packet lost. Permanently.",
    "Hold my beer... forever.",
    "This is fine. Everything is fine—",
    "Merge me into the void, baby.",
    "Death by hotfix. Typical.",
  ],
};

function pickFireSaying(category) {
  const bank = SAYINGS.fire[category] || SAYINGS.fire.default;
  return Utils.choice(bank);
}

function pickDeathSaying() {
  return Utils.choice(SAYINGS.death);
}
